Change desi_setup to support installation to a common prefix.

diff --git a/desi_setup b/desi_setup
--- a/desi_setup
+++ b/desi_setup
@@ -262,6 +262,125 @@ install_package () {
 }
 
 
+install_package_common () {
+    # This installs a package to the common prefix.  The setup
+    # of environment variables is simpler in this case.
+
+    local pkg="$1"
+    local pkgdir="$2"
+    local prefix="$3"
+    local setup="$4"
+    local outmod="$5"
+    local logroot="$6"
+
+    local mode="normal"
+
+    echo "Installing ${pkg} to common prefix" >&2
+
+    pushd "${pkgdir}" > /dev/null
+
+    get_pkg_version
+    pkgver="${global_get_version}"
+
+    local logfile=""
+    if [ "x${logroot}" = "x" ]; then
+        logfile="/dev/stderr"
+        mode="single"
+    else
+        logfile="${logroot}_${pkg}"
+        rm -f "${logfile}"
+    fi
+
+    # set package prefix
+    mkdir -p "${prefix}" >> "${logfile}" 2>&1
+    
+    # uppercase package name
+    local pkgup=$(echo ${pkg} | tr '[:lower:]' '[:upper:]')
+
+    # add lines to the shell-snippet alternative to modulefiles,
+    # as well as installing the module files.
+
+    echo "# Settings for ${pkg}" >> "${setup}"
+    echo "export DESI_${pkgup}_VERSION=\"${pkgver}\"" >> "${setup}"
+    echo "setenv DESI_${pkgup}_VERSION \"${pkgver}\"" >> "${outmod}"
+
+    # do the install
+    if [ "${pkg}" = "specex" ]; then
+
+        # This package has executables and compiled libraries
+        
+        export HARP_PLUGIN_PATH="${prefix}/lib"
+        echo "export HARP_PLUGIN_PATH=\"${prefix}/lib\"" >> "${setup}"
+        echo "setenv HARP_PLUGIN_PATH \"${prefix}/lib\"" >> "${outmod}"
+
+        eval "SPECEX_PREFIX=\"${prefix}\" make install" >> "${logfile}" 2>&1
+
+    elif [ "${pkg}" = "fiberassign" ]; then
+
+        # First install compiled code
+
+        eval "INSTALL=\"${prefix}/bin\" make install" >> "${logfile}" 2>&1
+
+        # Now copy scripts and python package into place
+
+        cp -a bin/* "${prefix}/bin/" >> "${logfile}" 2>&1
+        chmod -R +x "${prefix}/bin/" >> "${logfile}" 2>&1
+        cp -a py/fiberassign "${prefix}/lib/python${pysite}/site-packages/" >> "${logfile}" 2>&1
+
+        python -m compileall -f "${prefix}/lib/python${pysite}/site-packages" >> "${logfile}" 2>&1
+
+    elif [ "${pkg}" = "redmonster" ]; then
+
+        export REDMONSTER_TEMPLATES_DIR="${prefix}/templates"
+        echo "export REDMONSTER_TEMPLATES_DIR=\"${prefix}/templates\"" >> "${setup}"
+        echo "setenv REDMONSTER_TEMPLATES_DIR \"${prefix}/templates\"" >> "${outmod}"
+
+        # We just copy the source tree into the install prefix...
+
+        cp -a templates "${prefix}/" >> "${logfile}" 2>&1
+        cp -a conf "${prefix}/" >> "${logfile}" 2>&1
+        cp -a pro "${prefix}/" >> "${logfile}" 2>&1
+
+        cp -a bin/* "${prefix}/bin/" >> "${logfile}" 2>&1
+        chmod -R +x "${prefix}/bin/" >> "${logfile}" 2>&1
+        
+        cp -a python/redmonster "${prefix}/lib/python${pysite}/site-packages/" >> "${logfile}" 2>&1
+
+        python -m compileall -f "${prefix}/lib/python${pysite}/site-packages" >> "${logfile}" 2>&1
+
+    elif [ "${pkg}" = "teststand" ]; then
+
+        # We just copy the bin, data, and python directories
+        # into the prefix.
+
+        cp -a data "${prefix}/" >> "${logfile}" 2>&1
+
+        cp -a bin/* "${prefix}/bin/" >> "${logfile}" 2>&1
+        chmod -R +x "${prefix}/bin/" >> "${logfile}" 2>&1
+        
+        cp -a py/desispec_tools "${prefix}/lib/python${pysite}/site-packages/" >> "${logfile}" 2>&1
+
+        python -m compileall -f "${prefix}/lib/python${pysite}/site-packages" >> "${logfile}" 2>&1
+
+    else
+
+        # Assume that this is just a standard DESI python package
+
+        python setup.py install --prefix=${prefix} >> "${logfile}" 2>&1
+
+        python -m compileall -f "${prefix}/lib/python${pysite}/site-packages" >> "${logfile}" 2>&1
+
+    fi
+
+    echo "" >> "${setup}"
+    echo "" >> "${outmod}"
+    
+    popd > /dev/null
+
+    global_pkgver="${pkgver}"
+}
+
+
 install_packages () {
     # This function is run in a subshell.  As each package is installed,
     # it modifies the environment so that future packages can use previous
@@ -295,6 +414,66 @@ install_packages () {
     echo "${dephash}"
 }
 
+
+install_packages_common () {
+    # This function is run in a subshell.  As each package is installed,
+    # it modifies the environment so that future packages can use previous
+    # ones.  The parent shell environment is not modified.  The packages
+    # listed in the version file should be in order of increasing
+    # dependencies.
+
+    local versionfile="$1"
+    local prefix="$2"
+    local setup="$3"
+    local modfile="$4"
+    local logroot="$5"
+
+    # add the common prefix locations to setup and module file
+
+    mkdir -p "${prefix}/bin"
+    mkdir -p "${prefix}/include"
+    mkdir -p "${prefix}/lib/python${pysite}/site-packages"
+
+    export PATH="${prefix}/bin:${PATH}"
+    echo "export PATH=\"${prefix}/bin:\${PATH}\"" >> "${setup}"
+    echo "prepend-path PATH \"${prefix}/bin\"" >> "${modfile}"
+
+    export CPATH="${prefix}/include:${CPATH}"
+    echo "export CPATH=\"${prefix}/include:\${CPATH}\"" >> "${setup}"
+    echo "prepend-path CPATH \"${prefix}/include\"" >> "${modfile}"
+    
+    export LIBRARY_PATH="${prefix}/lib:${LIBRARY_PATH}"
+    echo "export LIBRARY_PATH=\"${prefix}/lib:\${LIBRARY_PATH}\"" >> "${setup}"
+    echo "prepend-path LIBRARY_PATH \"${prefix}/lib\"" >> "${modfile}"
+    
+    export LD_LIBRARY_PATH="${prefix}/lib:${LD_LIBRARY_PATH}"
+    echo "export LD_LIBRARY_PATH=\"${prefix}/lib:\${LD_LIBRARY_PATH}\"" >> "${setup}"
+    echo "prepend-path LD_LIBRARY_PATH \"${prefix}/lib\"" >> "${modfile}"
+
+    export PYTHONPATH="${prefix}/lib/python${pysite}/site-packages:${PYTHONPATH}"
+    echo "export PYTHONPATH=\"${prefix}/lib/python${pysite}/site-packages:\${PYTHONPATH}\"" >> "${setup}"
+    echo "prepend-path PYTHONPATH \"${prefix}/lib/python${pysite}/site-packages\"" >> "${modfile}"
+
+    echo "" >> "${setup}"
+    echo "" >> "${modfile}"
+
+    local dephash=""
+
+    local pkg=""
+    
+    while IFS='' read -r line || [[ -n "${line}" ]]; do
+        # get package name from versions file
+        pkg=$(echo ${line} | awk '{print $1}')
+
+        install_package_common "${pkg}" "${pkg}" "${prefix}" "${setup}" "${modfile}" "${logroot}"
+        pkgver="${global_pkgver}"
+        
+        dephash="${dephash}${pkgver}"
+
+    done < "${versionfile}"
+
+    echo "${dephash}"
+}
 
 
 prefix=""
@@ -374,14 +553,16 @@ buildver="${global_get_version}"
 popd > /dev/null
 
 if [ "x${single}" != "x" ]; then
-    # we are just installing a single package.  In this
-    # case, we will install a modulefile, but will not
-    # modify the main setup.sh shell snippet nor install
-    # a high-level desi module.
+    # we are just installing a single package.
 
     pkg=$(basename "${single}")
 
-    install_package "${pkg}" "${single}" "${prefix}" "/dev/null" "${moddir}" "${modtemplate}" "${vertemplate}" ""
+    if [ "${common}" = "yes" ]; then
+        setup="${prefix}/setup.sh"
+        install_package_common "${pkg}" "${single}" "${prefix}" "${setup}" "/dev/null" ""
+    else
+        install_package "${pkg}" "${single}" "${prefix}" "/dev/null" "${moddir}" "${modtemplate}" "${vertemplate}" ""
+    fi
     
     pkgver="${global_pkgver}"
 
@@ -397,7 +578,15 @@ else
     # process all packages
 
     logroot="${srcdir}/setup"
-    dephash=$(install_packages "${versionfile}" "${prefix}" "${setup}" "${moddir}" "${modtemplate}" "${vertemplate}" "${logroot}")
+
+    tempmod=""
+    if [ "${common}" = "yes" ]; then
+        tempmod="${srcdir}/tmp.module"
+        rm -f "${tempmod}"
+        dephash=$(install_packages_common "${versionfile}" "${prefix}" "${setup}" "${tempmod}" "${logroot}")
+    else
+        dephash=$(install_packages "${versionfile}" "${prefix}" "${setup}" "${moddir}" "${modtemplate}" "${vertemplate}" "${logroot}")
+    fi
 
     # Now we create a top-level module file that loads the others.
 
@@ -434,26 +623,50 @@ else
         cat "${moduleinit}" >> "${outmod}"
     fi
 
-    # iterate over the package versions and load them
+    if [ "${common}" = "yes" ]; then
+        # we just append all the per-package commands to the main
+        # desi module file.
 
-    while IFS='' read -r line || [[ -n "${line}" ]]; do
-        pkg=$(echo ${line} | awk '{print $1}')
-
-        # get package version from current git
-        cd "${pkg}"
-        get_pkg_version
-        pkgver="${global_get_version}"
+        if [ "x${tempmod}" = "x" ]; then
+            echo "\n\nERROR: Temporary package module command file name not set" >&2
+            echo "ERROR: This should never happen!\n\n" >&2
+            exit 1
+        fi
+        if [ ! -e "${tempmod}" ]; then
+            echo "\n\nERROR: Temporary package module command file does not exist" >&2
+            echo "ERROR: This likely means something failed during package installation" >&2
+            exit 1
+        fi
 
         echo "" >> "${outmod}"
-        echo "if [ module-info mode load ] {" >> "${outmod}"
-        echo "  if [ is-loaded ${pkg} ] {" >> "${outmod}"
-        echo "  } else {" >> "${outmod}"
-        echo "    module load ${pkg}/${pkgver}" >> "${outmod}"
-        echo "  }" >> "${outmod}"
-        echo "}" >> "${outmod}"
+        cat "${tempmod}" >> "${outmod}"
+        rm -f "${tempmod}"
 
-        cd ..
-    done < "${versionfile}"
+    else
+
+        # iterate over the package versions and append the commands
+        # to load them.
+
+        while IFS='' read -r line || [[ -n "${line}" ]]; do
+            pkg=$(echo ${line} | awk '{print $1}')
+
+            # get package version from current git
+            cd "${pkg}"
+            get_pkg_version
+            pkgver="${global_get_version}"
+
+            echo "" >> "${outmod}"
+            echo "if [ module-info mode load ] {" >> "${outmod}"
+            echo "  if [ is-loaded ${pkg} ] {" >> "${outmod}"
+            echo "  } else {" >> "${outmod}"
+            echo "    module load ${pkg}/${pkgver}" >> "${outmod}"
+            echo "  }" >> "${outmod}"
+            echo "}" >> "${outmod}"
+
+            cd ..
+        done < "${versionfile}"
+
+    fi
 
     echo "" >> "${outmod}"
 
